#!/usr/bin/env python3
"""
Auto-Commit Utility
Automatically stages and commits changes generated by Claude Code.
"""

import subprocess
import datetime
from logger import log, error, success

def is_git_repo(path: str) -> bool:
    result = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], cwd=path, capture_output=True)
    return result.returncode == 0

def auto_commit(workspace_path: str, message: str = None):
    if not is_git_repo(workspace_path):
        log("Workspace is not a git repository. Initializing...")
        subprocess.run(["git", "init"], cwd=workspace_path)
    
    log("Staging changes...")
    subprocess.run(["git", "add", "."], cwd=workspace_path)
    
    # Check if there are changes to commit
    status = subprocess.run(["git", "status", "--porcelain"], cwd=workspace_path, capture_output=True, text=True)
    if not status.stdout.strip():
        log("No changes detected by Git.")
        return

    commit_msg = message or f"T3rmux-x Auto-build: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    
    result = subprocess.run(["git", "commit", "-m", commit_msg], cwd=workspace_path, capture_output=True)
    if result.returncode == 0:
        success("Changes automatically committed.")
    else:
        error("Failed to auto-commit changes.")

if __name__ == "__main__":
    auto_commit(".")
